### ISSUE TITLE
请问类别顺序是什么？

### ISSUE THREAD

**Issue by zihuanqiu** [Impression2805/CVPR21_PASS#5]
代码里cifar的顺序是从0到99，这是论文里使用的顺序吗？对于其他的数据集呢？感谢～

**Comment by Impression2805** [comment]
你好，与其他工作中使用的顺序一致，三个数据集的类别顺序都是由随机种子1993产生的，cifar的顺序也在代码里更新了。

**Comment by zihuanqiu** [comment]
imagenet-subset的类别是从imagenet-1000中取的前100个类别还是按照随机种子1993选择后的前100个呢
